

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#      - id: fsh-house
#        uri: lb://fsh-house
#        predicates:
#        - Path=/house/**

  application:
    name: gateway0


server:
  port: 20002
#
#logging:
#    level:
#        ROOT: DEBUG
#        uaa: DEBUG
#        io.github.jhipster: DEBUG

eureka:
  instance:
    appname: gateway.01
#    prefer-ip-address: true
    instance-id: ${spring.application.name}
#    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka/
