

spring:
#  redis:
#      database: 0
#      host: 172.18.61.70
#      password: fengyun123456
#      port: 9701
#      pool:
#          max-idle: 8
#          min-idle: 0
#          max-active: 8
#          max-wait: -1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#      - id: fsh-house
#        uri: lb://fsh-house
#        predicates:
#        - Path=/house/**

  application:
    name: gateway0


server:
  port: 20002
#
#logging:
#    level:
#        ROOT: DEBUG
#        uaa: DEBUG
#        io.github.jhipster: DEBUG

eureka:
  enabled: true
  instance:
    appname: gateway
#    prefer-ip-address: true
    instance-id: ${spring.application.name}
#    hostname: ${spring.application.name}
  client:
#    healthcheck:
#      enabled: true
    service-url:
      defaultZone: http://localhost:20000/eureka/
